import type {
  Account,
  ActivityEvent,
  Challenge,
  ChallengeModel,
  ChartPoint,
  LeaderboardTrader,
  Payout,
  SearchResult,
  Trade,
  WorkspaceNotification,
} from "./types";

export const workspaceUser = {
  name: "Alex Morgan",
  initials: "AM",
  email: "alex.morgan@example.com",
  phone: "+44 7700 900 214",
  country: "United Kingdom",
  timezone: "Europe/London (UTC+1)",
  language: "English (UK)",
  level: "Disciplined Trader",
  memberSince: "12 January 2026",
  verification: "Identity verified",
  kycStatus: "Demo record — verified",
};

export const accounts: Account[] = [
  {
    id: "TF-82104",
    name: "Apex Evaluation 100K",
    size: 100000,
    category: "Evaluation",
    status: "Active",
    phase: "Phase 2",
    balance: 104260.8,
    equity: 104486.2,
    pnl: 4260.8,
    pnlPercent: 4.26,
    platform: "TradeLocker",
    createdAt: "12 Jan 2026",
    lastActivity: "24 Jul 2026, 14:42",
    health: "Good standing",
  },
  {
    id: "TF-91582",
    name: "Apex Evaluation 50K",
    size: 50000,
    category: "Evaluation",
    status: "Active",
    phase: "Phase 1",
    balance: 51180.2,
    equity: 51124.7,
    pnl: 1180.2,
    pnlPercent: 2.36,
    platform: "TradeLocker",
    createdAt: "08 Jul 2026",
    lastActivity: "24 Jul 2026, 11:18",
    health: "Good standing",
  },
  {
    id: "TF-67144",
    name: "Forge Funded 100K",
    size: 100000,
    category: "Funded",
    status: "Funded",
    phase: "Funded",
    balance: 102840,
    equity: 102840,
    pnl: 2840,
    pnlPercent: 2.84,
    platform: "TradeLocker",
    createdAt: "15 May 2026",
    lastActivity: "23 Jul 2026, 17:05",
    health: "Good standing",
  },
  {
    id: "TF-54419",
    name: "Apex Evaluation 25K",
    size: 25000,
    category: "Passed",
    status: "Passed",
    phase: "Complete",
    balance: 27012.5,
    equity: 27012.5,
    pnl: 2012.5,
    pnlPercent: 8.05,
    platform: "TradeLocker",
    createdAt: "03 Apr 2026",
    lastActivity: "26 Apr 2026, 09:30",
    health: "Closed",
  },
  {
    id: "TF-40273",
    name: "Apex Evaluation 50K",
    size: 50000,
    category: "Failed",
    status: "Failed",
    phase: "Phase 1",
    balance: 44920,
    equity: 44920,
    pnl: -5080,
    pnlPercent: -10.16,
    platform: "TradeLocker",
    createdAt: "14 Feb 2026",
    lastActivity: "02 Mar 2026, 16:21",
    health: "Closed",
  },
  {
    id: "TF-31808",
    name: "Apex Evaluation 10K",
    size: 10000,
    category: "Archived",
    status: "Archived",
    phase: "Complete",
    balance: 10422,
    equity: 10422,
    pnl: 422,
    pnlPercent: 4.22,
    platform: "TradeLocker",
    createdAt: "10 Jan 2026",
    lastActivity: "28 Jan 2026, 12:09",
    health: "Closed",
  },
];

export const challenges: Challenge[] = [
  {
    id: "challenge-100k",
    name: "Apex Evaluation 100K",
    accountId: "TF-82104",
    size: 100000,
    phase: "Phase 2",
    status: "Active",
    currentBalance: 104260.8,
    profit: 4260.8,
    profitTarget: 6000,
    dailyLossUsed: 1178.6,
    dailyLossLimit: 5000,
    overallLossUsed: 2640.8,
    overallLossLimit: 10000,
    tradingDays: 9,
    minimumTradingDays: 10,
    progress: 71,
    nextMilestone: "Complete one more trading day and reach $106,000",
  },
  {
    id: "challenge-50k",
    name: "Apex Evaluation 50K",
    accountId: "TF-91582",
    size: 50000,
    phase: "Phase 1",
    status: "Active",
    currentBalance: 51180.2,
    profit: 1180.2,
    profitTarget: 4000,
    dailyLossUsed: 420,
    dailyLossLimit: 2500,
    overallLossUsed: 875,
    overallLossLimit: 5000,
    tradingDays: 4,
    minimumTradingDays: 5,
    progress: 30,
    nextMilestone: "Record one more trading day",
  },
  {
    id: "challenge-passed",
    name: "Apex Evaluation 25K",
    accountId: "TF-54419",
    size: 25000,
    phase: "Phase 2",
    status: "Passed",
    currentBalance: 27012.5,
    profit: 2012.5,
    profitTarget: 2000,
    dailyLossUsed: 155,
    dailyLossLimit: 1250,
    overallLossUsed: 430,
    overallLossLimit: 2500,
    tradingDays: 8,
    minimumTradingDays: 5,
    progress: 100,
    nextMilestone: "Evaluation complete",
  },
];

export const challengeModels: ChallengeModel[] = [
  {
    id: "apex-two-step",
    name: "Apex two-step",
    description: "Measured targets with a second verification phase.",
    phases: 2,
    profitTarget: "8% then 6%",
    dailyLossLimit: "5%",
    overallLossLimit: "10%",
    tradingDays: "5 per phase",
    sizes: [10000, 25000, 50000, 100000],
    recommended: true,
  },
  {
    id: "forge-one-step",
    name: "Forge one-step",
    description: "A single evaluation with tighter risk parameters.",
    phases: 1,
    profitTarget: "10%",
    dailyLossLimit: "4%",
    overallLossLimit: "8%",
    tradingDays: "5 minimum",
    sizes: [25000, 50000, 100000],
  },
  {
    id: "swing-two-step",
    name: "Swing two-step",
    description: "Wider holding flexibility for planned swing strategies.",
    phases: 2,
    profitTarget: "8% then 5%",
    dailyLossLimit: "5%",
    overallLossLimit: "10%",
    tradingDays: "5 per phase",
    sizes: [50000, 100000, 200000],
  },
];

export const payouts: Payout[] = [
  {
    id: "payout-1",
    reference: "PC-0042",
    requestedAt: "14 Jul 2026",
    processedAt: "18 Jul 2026",
    amount: 1280,
    method: "Bank transfer",
    status: "Completed",
    note: "Completed after demo review.",
  },
  {
    id: "payout-2",
    reference: "PC-0038",
    requestedAt: "02 Jul 2026",
    processedAt: "04 Jul 2026",
    amount: 960,
    method: "Bank transfer",
    status: "Completed",
    note: "Completed after demo review.",
  },
  {
    id: "payout-3",
    reference: "PC-0031",
    requestedAt: "20 Jun 2026",
    processedAt: "23 Jun 2026",
    amount: 720,
    method: "USDC",
    status: "Completed",
    note: "Completed after demo review.",
  },
  {
    id: "payout-4",
    reference: "PC-0027",
    requestedAt: "01 Jun 2026",
    processedAt: "03 Jun 2026",
    amount: 540,
    method: "Bank transfer",
    status: "Completed",
    note: "Completed after demo review.",
  },
  {
    id: "payout-5",
    reference: "PC-0046",
    requestedAt: "22 Jul 2026",
    processedAt: "In review",
    amount: 840,
    method: "Bank transfer",
    status: "Pending",
    note: "Demo request awaiting compliance review.",
  },
  {
    id: "payout-6",
    reference: "PC-0022",
    requestedAt: "08 May 2026",
    processedAt: "09 May 2026",
    amount: 420,
    method: "USDC",
    status: "Rejected",
    note: "Demo record: eligibility window had not opened.",
  },
];

export const leaderboardTraders: LeaderboardTrader[] = [
  { id: "trader-1", rank: 1, alias: "OrbitAlpha", country: "GB", accountSize: 200000, weeklyReturn: 6.84, monthlyReturn: 14.26, winRate: 72, profitFactor: 2.31, badge: "Consistent" },
  { id: "trader-2", rank: 2, alias: "NorthstarFX", country: "CA", accountSize: 100000, weeklyReturn: 6.12, monthlyReturn: 13.88, winRate: 69, profitFactor: 2.18, badge: "Risk control" },
  { id: "trader-3", rank: 3, alias: "DeltaForge", country: "AE", accountSize: 200000, weeklyReturn: 5.74, monthlyReturn: 13.41, winRate: 67, profitFactor: 2.04, badge: "Momentum" },
  { id: "trader-4", rank: 4, alias: "LondonOpen", country: "GB", accountSize: 100000, weeklyReturn: 5.19, monthlyReturn: 12.92, winRate: 65, profitFactor: 1.96, badge: "Consistent" },
  { id: "trader-5", rank: 5, alias: "AtlasEdge", country: "US", accountSize: 50000, weeklyReturn: 4.88, monthlyReturn: 11.76, winRate: 64, profitFactor: 1.89, badge: "Breakout" },
  { id: "trader-6", rank: 6, alias: "CalmExecution", country: "IN", accountSize: 100000, weeklyReturn: 4.62, monthlyReturn: 11.21, winRate: 68, profitFactor: 1.91, badge: "Risk control" },
  { id: "trader-7", rank: 7, alias: "TokyoRange", country: "JP", accountSize: 50000, weeklyReturn: 4.21, monthlyReturn: 10.64, winRate: 61, profitFactor: 1.78, badge: "Consistent" },
  { id: "trader-8", rank: 8, alias: "MacroPulse", country: "DE", accountSize: 200000, weeklyReturn: 3.97, monthlyReturn: 10.18, winRate: 59, profitFactor: 1.72, badge: "Momentum" },
  { id: "trader-9", rank: 9, alias: "SessionMap", country: "SG", accountSize: 100000, weeklyReturn: 3.75, monthlyReturn: 9.87, winRate: 62, profitFactor: 1.69, badge: "Risk control" },
  { id: "trader-10", rank: 10, alias: "CedarTrades", country: "NZ", accountSize: 50000, weeklyReturn: 3.41, monthlyReturn: 9.22, winRate: 58, profitFactor: 1.62, badge: "Breakout" },
  { id: "trader-11", rank: 11, alias: "MeasuredMove", country: "AU", accountSize: 25000, weeklyReturn: 3.18, monthlyReturn: 8.74, winRate: 57, profitFactor: 1.58, badge: "Consistent" },
  { id: "trader-12", rank: 12, alias: "RiskFirst", country: "NL", accountSize: 100000, weeklyReturn: 2.96, monthlyReturn: 8.31, winRate: 60, profitFactor: 1.61, badge: "Risk control" },
];

export const notifications: WorkspaceNotification[] = [
  { id: "notice-1", title: "Daily loss usage is back below 25%", description: "Apex Evaluation 100K has $3,821.40 of today’s daily loss limit available.", timestamp: "16 minutes ago", category: "Rule alert", unread: true, href: "/" },
  { id: "notice-2", title: "Trading day 9 recorded", description: "One more qualifying day remains for Apex Evaluation 100K.", timestamp: "Yesterday", category: "Challenge", unread: true, href: "/challenges" },
  { id: "notice-3", title: "Demo payout request moved to review", description: "Request PC-0046 is awaiting the next mock compliance step.", timestamp: "22 Jul 2026", category: "Payout", unread: true, href: "/payouts" },
  { id: "notice-4", title: "Statement is ready", description: "Your June performance statement is available to download.", timestamp: "20 Jul 2026", category: "Account", unread: false, href: "/profile" },
  { id: "notice-5", title: "Phase 2 target reached 71%", description: "Current profit is $4,260.80 against a $6,000 target.", timestamp: "18 Jul 2026", category: "Challenge", unread: false, href: "/challenges" },
  { id: "notice-6", title: "New sign-in to demo workspace", description: "Chrome on Windows in London, United Kingdom.", timestamp: "17 Jul 2026", category: "System", unread: false, href: "/profile" },
  { id: "notice-7", title: "Account health confirmed", description: "No active rule breaches were found in the last daily review.", timestamp: "15 Jul 2026", category: "Account", unread: false, href: "/accounts" },
];

export const recentTrades: Trade[] = [
  { id: "trade-1", symbol: "EUR/USD", side: "Buy", closedAt: "24 Jul, 14:42", pnl: 480, riskReward: 2.4, duration: "1h 18m" },
  { id: "trade-2", symbol: "XAU/USD", side: "Sell", closedAt: "24 Jul, 11:18", pnl: -165, riskReward: -0.8, duration: "42m" },
  { id: "trade-3", symbol: "GBP/USD", side: "Buy", closedAt: "23 Jul, 16:05", pnl: 328, riskReward: 1.9, duration: "2h 06m" },
  { id: "trade-4", symbol: "NAS100", side: "Sell", closedAt: "23 Jul, 09:51", pnl: 612, riskReward: 2.8, duration: "55m" },
  { id: "trade-5", symbol: "USD/JPY", side: "Buy", closedAt: "22 Jul, 13:14", pnl: 204, riskReward: 1.5, duration: "1h 37m" },
];

export const activityFeed: ActivityEvent[] = [
  { id: "event-1", title: "EUR/USD position closed", description: "+$480.00 realised PnL with 2.4R.", timestamp: "14 minutes ago", type: "Trade" },
  { id: "event-2", title: "Trading day recorded", description: "9 of 10 minimum trading days complete.", timestamp: "Yesterday", type: "Challenge" },
  { id: "event-3", title: "Demo payout moved to review", description: "PC-0046 is pending mock compliance review.", timestamp: "22 Jul 2026", type: "Payout" },
  { id: "event-4", title: "Daily statement generated", description: "Statement for 21 July is ready.", timestamp: "21 Jul 2026", type: "Account" },
  { id: "event-5", title: "Risk check completed", description: "No active rule breaches found.", timestamp: "20 Jul 2026", type: "System" },
];

export const performanceData: ChartPoint[] = [
  { date: "01 Jul", balance: 100000, equity: 100000 },
  { date: "02 Jul", balance: 100420, equity: 100610 },
  { date: "03 Jul", balance: 100180, equity: 100260 },
  { date: "04 Jul", balance: 100940, equity: 101120 },
  { date: "07 Jul", balance: 101380, equity: 101240 },
  { date: "08 Jul", balance: 101720, equity: 101980 },
  { date: "09 Jul", balance: 101440, equity: 101580 },
  { date: "10 Jul", balance: 102160, equity: 102320 },
  { date: "11 Jul", balance: 101920, equity: 102080 },
  { date: "14 Jul", balance: 102740, equity: 102920 },
  { date: "15 Jul", balance: 103240, equity: 103110 },
  { date: "16 Jul", balance: 102880, equity: 103020 },
  { date: "17 Jul", balance: 103520, equity: 103760 },
  { date: "18 Jul", balance: 103980, equity: 104140 },
  { date: "21 Jul", balance: 103660, equity: 103880 },
  { date: "22 Jul", balance: 104020, equity: 104270 },
  { date: "23 Jul", balance: 103780, equity: 104010 },
  { date: "24 Jul", balance: 104260.8, equity: 104486.2 },
];

export const searchResults: SearchResult[] = [
  { id: "search-1", title: "Apex Evaluation 100K", description: "Active Phase 2 account · TF-82104", type: "Account", href: "/accounts", keywords: ["100k", "active", "phase 2", "tf-82104"] },
  { id: "search-2", title: "Apex Evaluation 50K", description: "Active Phase 1 account · TF-91582", type: "Account", href: "/accounts", keywords: ["50k", "active", "phase 1", "tf-91582"] },
  { id: "search-3", title: "Profit target rule", description: "How realised profit contributes to evaluation progress.", type: "Help", href: "/challenges", keywords: ["rules", "profit target", "objective"] },
  { id: "search-4", title: "Daily loss rule", description: "Review daily loss calculation and reset timing.", type: "Help", href: "/challenges", keywords: ["rules", "drawdown", "daily loss", "risk"] },
  { id: "search-5", title: "PC-0046", description: "Pending demo payout · $840.00", type: "Payout", href: "/payouts", keywords: ["payout", "pending", "840"] },
  { id: "search-6", title: "Apex two-step", description: "Two-phase challenge model with measured targets.", type: "Challenge", href: "/challenges", keywords: ["challenge", "model", "two step"] },
  { id: "search-7", title: "Maximum drawdown rule", description: "Understand the overall loss boundary for an account.", type: "Help", href: "/challenges", keywords: ["rules", "maximum", "overall", "drawdown"] },
];

export const loginActivity = [
  { id: "login-1", device: "Chrome on Windows", location: "London, United Kingdom", timestamp: "24 Jul 2026, 18:12", current: true },
  { id: "login-2", device: "Safari on iPhone", location: "London, United Kingdom", timestamp: "23 Jul 2026, 08:42", current: false },
  { id: "login-3", device: "Edge on Windows", location: "Manchester, United Kingdom", timestamp: "17 Jul 2026, 13:05", current: false },
];
