import Link from "next/link";
import { getAdminOverview } from "@/features/admin/admin-service";
import { PageHeader } from "@/components/workspace/page-header";
import { SectionCard } from "@/components/workspace/section-card";

export default async function AdminPage() {
  const overview = await getAdminOverview();
  const cards = [["Users", overview.totals.profiles, "/admin/users"], ["Orders", overview.totals.orders, "/admin/orders"], ["Accounts", overview.totals.accounts, "/admin/accounts"], ["Payouts", overview.totals.payout_requests, "/admin/payouts"]];
  return <div className="grid gap-6"><PageHeader eyebrow="Admin" title="Operations workspace" description="Live operational counts from the TradeForge database." /><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, href]) => <Link key={label} href={String(href)} className="rounded-tf-lg border border-border bg-card p-5 hover:border-primary"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p></Link>)}</section><section className="grid gap-3 md:grid-cols-3"><SectionCard title="Orders" description="Status distribution."><div className="grid gap-2 text-sm">{Object.entries(overview.orders).map(([status, count]) => <div key={status} className="flex justify-between"><span className="text-muted-foreground">{status}</span><strong>{count}</strong></div>)}</div></SectionCard><SectionCard title="Accounts" description="Lifecycle distribution."><div className="grid gap-2 text-sm">{Object.entries(overview.accounts).map(([status, count]) => <div key={status} className="flex justify-between"><span className="text-muted-foreground">{status}</span><strong>{count}</strong></div>)}</div></SectionCard><SectionCard title="Payouts" description="Review queue distribution."><div className="grid gap-2 text-sm">{Object.entries(overview.payouts).map(([status, count]) => <div key={status} className="flex justify-between"><span className="text-muted-foreground">{status}</span><strong>{count}</strong></div>)}</div></SectionCard></section></div>;
}