import { ArrowUpRight, BadgeCheck, MoreHorizontal } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { accountSummary, trustNote } from "./mock-data";

export function AccountOverview() {
  const TrustIcon = trustNote.icon;
  return <Card className="relative overflow-hidden p-0"><div className="absolute -right-12 -top-20 size-64 rounded-full bg-primary/10 blur-3xl" /><div className="relative flex flex-col gap-6 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><Badge status="phase2">{accountSummary.phase}</Badge><Badge status="success">{accountSummary.status}</Badge></div><h3 className="mt-3 text-xl">{accountSummary.name}</h3><p className="mt-1 text-sm text-muted-foreground">{accountSummary.accountId} · {accountSummary.platform}</p></div><Button variant="ghost" size="icon" aria-label="Account options"><MoreHorizontal className="size-5" /></Button></div><div className="grid gap-5 sm:grid-cols-3"><div><p className="text-xs font-medium uppercase tracking-[.12em] text-muted-foreground">Current balance</p><p className="mt-2 font-display text-3xl font-semibold tracking-tight">{accountSummary.balance}</p><p className="mt-1 text-xs text-muted-foreground">Started at {accountSummary.initialBalance}</p></div><div className="rounded-tf-md border border-white/[.08] bg-white/[.035] p-4"><p className="text-xs text-muted-foreground">Account status</p><p className="mt-2 flex items-center gap-2 text-sm font-semibold text-success"><BadgeCheck className="size-4" />Verified evaluation</p></div><div className="rounded-tf-md border border-white/[.08] bg-white/[.035] p-4"><p className="text-xs text-muted-foreground">{trustNote.label}</p><p className="mt-2 flex items-center gap-2 text-sm font-semibold"><TrustIcon className="size-4 text-primary" />{trustNote.value}</p></div></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4"><p className="text-sm text-muted-foreground">{accountSummary.complianceLabel}</p><Button variant="outline" size="sm">Account details <ArrowUpRight className="size-4" /></Button></div></div></Card>;
}
