"use client";
import { Activity, Bell, ChevronRight, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, ChallengeCard, InfoCard, PricingCard, ProfileCard, StatCard } from "@/components/ui/card";
import { Checkbox, Radio, SelectField, Switch } from "@/components/ui/control";
import { DataTable, type Column } from "@/components/ui/data-table";
import { Field, Input, PasswordInput, SearchInput, Textarea } from "@/components/ui/input";
import { ActionModal } from "@/components/ui/modal";
const rows = [{ id: "1", trader: "Ethan Williams", account: "TF-82104", status: "Funded", pnl: "+$2,840" }, { id: "2", trader: "Mia Cooper", account: "TF-21856", status: "Phase 2", pnl: "+$1,260" }, { id: "3", trader: "Lucas Reed", account: "TF-61190", status: "Failed", pnl: "-$340" }];
const columns: Column<(typeof rows)[number]>[] = [{ key: "trader", label: "Trader" }, { key: "account", label: "Account" }, { key: "status", label: "Status", render: (v) => <Badge status={v === "Funded" ? "funded" : v === "Failed" ? "failed" : "phase2"}>{v}</Badge> }, { key: "pnl", label: "P&L", render: (v) => <span className={String(v).startsWith("+") ? "text-success" : "text-danger"}>{v}</span> }];
function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) { return <section className="border-t border-border py-12"><div className="mb-7"><h2 className="text-2xl">{title}</h2>{description && <p className="mt-2 text-sm text-muted-foreground">{description}</p>}</div>{children}</section>; }
export default function DesignSystemPage() { return <main className="content-container pb-20"><header className="flex items-center justify-between py-7"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-tf-sm bg-primary font-display font-bold shadow-glow">T</span><span className="font-display text-lg font-bold">TradeForge</span><span className="hidden rounded-full border border-border px-2 py-0.5 text-[10px] uppercase tracking-wider text-muted-foreground sm:inline">Design System</span></div><Button variant="ghost" size="icon" aria-label="Notifications"><Bell className="size-4" /></Button></header><div className="py-12 sm:py-20"><p className="mb-4 text-sm font-semibold uppercase tracking-[.18em] text-primary">Foundation · v0.1</p><h1>Precision in every interface.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-muted-foreground">A premium dark-mode component foundation for TradeForge products: decisive, clear, and built for trust.</p></div>
<Section title="Foundation" description="Core palette, typography, spacing and elevation rules."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Background", "bg-background"], ["Surface", "bg-surface"], ["Card", "bg-card"], ["Primary", "bg-primary"]].map(([name, cls]) => <div key={name} className={`h-24 rounded-tf-lg border border-border ${cls} p-4 text-sm font-semibold`}>{name}</div>)}</div><div className="mt-8 grid gap-3"><p className="font-display text-3xl font-semibold">Display — Manrope</p><p className="text-base">Body — DM Sans. Spacing follows a 4px base unit; containers: 1280px max; radii: 8 / 12 / 16 / 20px.</p><p className="text-xs text-muted-foreground">Caption — Supporting data, timestamps and metadata.</p></div></Section>
<Section title="Buttons"><div className="flex flex-wrap items-center gap-3"><Button>Primary <ChevronRight className="size-4" /></Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Danger</Button><Button loading>Loading</Button><Button disabled>Disabled</Button></div></Section>
<Section title="Form controls"><div className="grid max-w-3xl gap-5 sm:grid-cols-2"><Field label="Email address"><Input placeholder="trader@tradeforge.com" /></Field><Field label="Password" hint="Minimum 8 characters"><PasswordInput placeholder="Enter password" /></Field><Field label="Search"><SearchInput placeholder="Search accounts" /></Field><Field label="Account type"><SelectField items={["Evaluation", "Funded", "Direct"]} /></Field><div className="flex flex-wrap gap-5"><Checkbox label="Remember me" defaultChecked /><Radio label="Standard plan" name="plan" defaultChecked /><Switch label="Price alerts" /></div><Field label="Message"><Textarea placeholder="Tell us how we can help." /></Field></div></Section>
<Section title="Cards"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><StatCard label="Total payout" value="$48,420" trend="12.5%" /><ChallengeCard title="Apex 100K" phase="Phase 2" balance="$104,260" progress={68} /><PricingCard plan="Professional" price="$499" highlighted features={["100K account", "80% profit split", "Daily payouts"]} /><ProfileCard name="Alex Morgan" role="Funded trader" initials="AM" /><InfoCard title="Trading status">Markets are open. Your risk limits refresh at midnight UTC.</InfoCard></div></Section>
<Section title="Badges"><div className="flex flex-wrap gap-2"><Badge status="success">Success</Badge><Badge status="failed">Failed</Badge><Badge status="funded">Funded</Badge><Badge status="phase1">Phase 1</Badge><Badge status="phase2">Phase 2</Badge><Badge status="verified">Verified</Badge></div></Section>
<Section title="Data table" description="Sortable columns, status tags, and lightweight client-side pagination."><DataTable columns={columns} rows={rows} /></Section>
<Section title="Modals"><div className="flex flex-wrap gap-3"><ActionModal kind="confirmation" trigger={<Button>Confirmation</Button>} /><ActionModal kind="success" trigger={<Button variant="outline">Success</Button>} /><ActionModal kind="warning" trigger={<Button variant="secondary">Warning</Button>} /><ActionModal kind="delete" trigger={<Button variant="danger">Delete</Button>} /></div></Section>
</main>; }
