import { notFound } from "next/navigation";
import { getAdminOrder } from "@/features/admin/admin-service";
import { AdminReconcilePayment } from "@/features/admin/admin-actions";
import { PageHeader } from "@/components/workspace/page-header";
import { SectionCard } from "@/components/workspace/section-card";
import { StatusBadge } from "@/components/workspace/status-badge";

export default async function AdminOrderDetailPage({ params }: { params: Promise<{ id: string }> }) {
  try { const order = await getAdminOrder((await params).id); if (!order) notFound(); return <div className="grid gap-6"><PageHeader eyebrow="Admin / Orders" title="Order lifecycle" description={order.id} action={order.status === "payment_pending" ? <AdminReconcilePayment orderId={order.id} /> : undefined} /><section className="grid gap-3 md:grid-cols-2"><SectionCard title="Lifecycle"><div className="grid gap-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Challenge plan</span><span>{order.challenge_plan_id}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Order</span><span>{order.id}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Payment</span><StatusBadge tone={order.status === "paid" ? "success" : "warning"}>{order.status}</StatusBadge></div><div className="flex justify-between"><span className="text-muted-foreground">Purchase</span><span>{order.status === "paid" ? "Created by verification" : "Not created"}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Account</span><span>{order.status === "paid" ? "Provisioning follows purchase" : "Not available"}</span></div></div></SectionCard><SectionCard title="Verification details"><div className="grid gap-2 text-sm"><span>Method: {order.payment_method ?? "Unavailable"}</span><span>Network: {order.payment_network ?? "Unavailable"}</span><span>Receiving wallet: {order.payment_address ?? "Unavailable"}</span><span>Transaction: {order.transaction_hash ?? order.payment_transaction_hint ?? "Not submitted"}</span><span>Verified at: {order.verified_at ? new Date(order.verified_at).toLocaleString() : "Not verified"}</span></div></SectionCard></section></div>; } catch { notFound(); }
}