"use client";
import * as React from "react";
import * as Select from "@radix-ui/react-select";
import { Check, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";
export function Checkbox({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="inline-flex cursor-pointer items-center gap-2 text-sm text-muted-foreground"><input type="checkbox" className="size-4 rounded border-border bg-surface accent-[hsl(var(--primary))]" {...props} />{label}</label>; }
export function Radio({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="inline-flex cursor-pointer items-center gap-2 text-sm text-muted-foreground"><input type="radio" className="size-4 border-border bg-surface accent-[hsl(var(--primary))]" {...props} />{label}</label>; }
export function Switch({ label, checked, onCheckedChange }: { label: string; checked?: boolean; onCheckedChange?: (value: boolean) => void }) { const [local, setLocal] = React.useState(checked ?? false); const value = checked ?? local; return <label className="inline-flex cursor-pointer items-center gap-2.5 text-sm text-muted-foreground"><button type="button" role="switch" aria-checked={value} onClick={() => { setLocal(!value); onCheckedChange?.(!value); }} className={cn("relative h-6 w-11 rounded-full transition-colors", value ? "bg-primary" : "bg-muted")}><span className={cn("absolute top-1 size-4 rounded-full bg-white transition-transform", value ? "translate-x-6" : "translate-x-1")} /></button>{label}</label>; }
export function SelectField({ placeholder = "Select an option", items }: { placeholder?: string; items: string[] }) { return <Select.Root><Select.Trigger className="flex h-11 w-full items-center justify-between rounded-tf-md border border-border bg-surface px-3 text-sm text-muted-foreground hover:border-white/20"><Select.Value placeholder={placeholder} /><ChevronDown className="size-4" /></Select.Trigger><Select.Portal><Select.Content position="popper" className="z-50 mt-1 min-w-[var(--radix-select-trigger-width)] overflow-hidden rounded-tf-md border border-border bg-card p-1 shadow-card"><Select.Viewport>{items.map((item) => <Select.Item value={item} key={item} className="relative cursor-pointer rounded px-8 py-2 text-sm text-muted-foreground outline-none data-[highlighted]:bg-white/[.06] data-[highlighted]:text-foreground"><Select.ItemText>{item}</Select.ItemText><Select.ItemIndicator className="absolute left-2"><Check className="size-4 text-primary" /></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root>; }
